//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hipica.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruta
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Duracion { get; set; }
        public decimal Precio { get; set; }
        public int Id_Nivel { get; set; }
        public string Descripcion { get; set; }
        public string Ruta_Imagen { get; set; }
    
        public virtual Nivel Nivel { get; set; }
    }
}
